apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.appPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}
