spring:
  application:
    name: upload-documents
elasticsearch:
  url: http://elasticsearch:9200
s3:
  region: eu-west-3
  endpoint-url: http://localstack:4572
  endpoint-path-style-enabled: true
documents:
  index: sigma.documents
  bucket: sigma.files
  uploadTimeout: 300
