apiVersion: v1
kind: Service
metadata:
  name: aws-upload
  labels:
    app: aws-upload
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30800
    protocol: TCP
    name: http
  selector:
    app: aws-upload
